//! The one supported GGUF, as `aqueduct doctor` needs it before the file exists on this machine: its
//! name, size, sha256, download URL, and the layout the memory plan is computed from. GENERATED by
//! `tools/gen_known_layout.py` from `tests/fixtures/gguf_index.json` and `tests/fixtures/gguf_metadata.json`
//! (both captured from the file itself in Phase 0); the tests below check this table against the fixture
//! always and against the real file whenever it is present. Do not edit by hand.

use aqueduct_core::tier::PlanInput;

pub const FILE_NAME: &str = "Qwen3.8-27B-Q4_K_M.gguf";
pub const REPO: &str = "bartowski/Qwen3.8-27B-GGUF";
pub const URL: &str = "https://huggingface.co/bartowski/Qwen3.8-27B-GGUF/resolve/main/Qwen3.8-27B-Q4_K_M.gguf";
pub const FILE_SIZE: u64 = 17772537440;
/// sha256 of the file (Hugging Face LFS object id; verified against the local copy on 2026-09-06).
pub const SHA256: &str = "e103abf9d914d1d7b2f2592f055f2759a71195c350a01c135f71aaae86bca52b";
pub const N_LAYER: u32 = 64;

/// Per layer `0..65`: (span start, span end) in the file, and the resident small-tensor bytes.
const LAYERS: [(u64, u64, u64); 65] = [
    (1769121376, 2038802912, 205696), // blk.0
    (2038802912, 2308484448, 205696), // blk.1
    (2308484448, 2578165984, 205696), // blk.2
    (2578165984, 2832734432, 43008), // blk.3
    (2832734432, 3102415968, 205696), // blk.4
    (3102415968, 3372097504, 205696), // blk.5
    (3372097504, 3641779040, 205696), // blk.6
    (3641779040, 3896347488, 43008), // blk.7
    (3896347488, 4127321824, 205696), // blk.8
    (4127321824, 4358296160, 205696), // blk.9
    (4358296160, 4627977696, 205696), // blk.10
    (4627977696, 4841995744, 43008), // blk.11
    (4841995744, 5072970080, 205696), // blk.12
    (5072970080, 5326922976, 205696), // blk.13
    (5326922976, 5573625952, 205696), // blk.14
    (5573625952, 5787644000, 43008), // blk.15
    (5787644000, 6041596896, 205696), // blk.16
    (6041596896, 6272571232, 205696), // blk.17
    (6272571232, 6519274208, 205696), // blk.18
    (6519274208, 6773842656, 43008), // blk.19
    (6773842656, 7004816992, 205696), // blk.20
    (7004816992, 7235791328, 205696), // blk.21
    (7235791328, 7505472864, 205696), // blk.22
    (7505472864, 7719490912, 43008), // blk.23
    (7719490912, 7950465248, 205696), // blk.24
    (7950465248, 8204418144, 205696), // blk.25
    (8204418144, 8451121120, 205696), // blk.26
    (8451121120, 8665139168, 43008), // blk.27
    (8665139168, 8919092064, 205696), // blk.28
    (8919092064, 9150066400, 205696), // blk.29
    (9150066400, 9396769376, 205696), // blk.30
    (9396769376, 9651337824, 43008), // blk.31
    (9651337824, 9882312160, 205696), // blk.32
    (9882312160, 10113286496, 205696), // blk.33
    (10113286496, 10382968032, 205696), // blk.34
    (10382968032, 10596986080, 43008), // blk.35
    (10596986080, 10827960416, 205696), // blk.36
    (10827960416, 11081913312, 205696), // blk.37
    (11081913312, 11328616288, 205696), // blk.38
    (11328616288, 11542634336, 43008), // blk.39
    (11542634336, 11796587232, 205696), // blk.40
    (11796587232, 12027561568, 205696), // blk.41
    (12027561568, 12274264544, 205696), // blk.42
    (12274264544, 12528832992, 43008), // blk.43
    (12528832992, 12759807328, 205696), // blk.44
    (12759807328, 12990781664, 205696), // blk.45
    (12990781664, 13260463200, 205696), // blk.46
    (13260463200, 13474481248, 43008), // blk.47
    (13474481248, 13705455584, 205696), // blk.48
    (13705455584, 13959408480, 205696), // blk.49
    (13959408480, 14206111456, 205696), // blk.50
    (14206111456, 14420129504, 43008), // blk.51
    (14420129504, 14674082400, 205696), // blk.52
    (14674082400, 14905056736, 205696), // blk.53
    (14905056736, 15151759712, 205696), // blk.54
    (15151759712, 15406328160, 43008), // blk.55
    (15406328160, 15676009696, 205696), // blk.56
    (15676009696, 15945691232, 205696), // blk.57
    (15945691232, 16215372768, 205696), // blk.58
    (16215372768, 16469941216, 43008), // blk.59
    (16469941216, 16739622752, 205696), // blk.60
    (16739622752, 17009304288, 205696), // blk.61
    (17009304288, 17278985824, 205696), // blk.62
    (17278985824, 17533554272, 43008), // blk.63
    (17533554272, 17772537440, 104448), // blk.64
];

/// Non-layer tensors in file order: (name, bytes).
const NON_LAYER: [(&str, u64); 3] = [
    ("output.weight", 1042944000),
    ("output_norm.weight", 20480),
    ("token_embd.weight", 715161600),
];

/// What `PlanInput::new(&gguf, &config)` builds from the file, without the file.
pub fn plan_input() -> PlanInput {
    let layer_span: Vec<(u64, u64)> = LAYERS[..N_LAYER as usize].iter().map(|&(s, e, _)| (s, e)).collect();
    let layer_small: Vec<u64> = LAYERS[..N_LAYER as usize].iter().map(|&(_, _, b)| b).collect();
    let mtp: Vec<(u32, u64, u64)> = (N_LAYER as usize..LAYERS.len()).map(|i| (i as u32, LAYERS[i].1 - LAYERS[i].0, LAYERS[i].0)).collect();
    PlanInput {
        non_layer: NON_LAYER.iter().map(|&(n, b)| (n.to_string(), b)).collect(),
        non_layer_region: Some((10995296, 1769121376)),
        mtp,
        layer_span,
        layer_small,
        n_layer: N_LAYER,
        n_deltanet: 48,
        n_attention: 16,
        hidden: 5120,
        inter: 17408,
        vocab: 248320,
        dn_conv_dim: 10240,
        dn_n_v: 48,
        dn_dk: 128,
        dn_dv: 128,
        dn_kernel: 4,
        n_head: 24,
        n_head_kv: 4,
        head_dim: 256,
        rope_dim: 64,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use aqueduct_core::tier::RESIDENT_SMALL;
    use std::path::{Path, PathBuf};

    fn root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
    }

    fn layer_of(name: &str) -> Option<usize> {
        let rest = name.strip_prefix("blk.")?;
        let end = rest.find('.')?;
        rest[..end].parse().ok()
    }

    /// A second derivation of the table from the fixture, in Rust: spans, small bytes, the non-layer
    /// region and the sizes must agree with what the generator wrote.
    #[test]
    fn table_matches_the_gguf_index_fixture() {
        let text = std::fs::read_to_string(root().join("tests/fixtures/gguf_index.json")).expect("tests/fixtures/gguf_index.json");
        let j: serde_json::Value = serde_json::from_str(&text).expect("json");
        assert_eq!(j["file"].as_str().unwrap(), FILE_NAME);
        assert_eq!(j["file_size"].as_u64().unwrap(), FILE_SIZE);
        let tensors = j["tensors"].as_array().unwrap();
        let n_blocks = LAYERS.len();
        let mut start = vec![u64::MAX; n_blocks];
        let mut end = vec![0u64; n_blocks];
        let mut small = vec![0u64; n_blocks];
        let mut non_layer: Vec<(String, u64)> = Vec::new();
        let (mut nl_start, mut nl_end, mut nl_sum) = (u64::MAX, 0u64, 0u64);
        for t in tensors {
            let name = t["name"].as_str().unwrap();
            let (off, size, fin) = (t["byte_offset"].as_u64().unwrap(), t["byte_size"].as_u64().unwrap(), t["byte_end"].as_u64().unwrap());
            match layer_of(name) {
                Some(l) => {
                    assert!(l < n_blocks, "{name}");
                    start[l] = start[l].min(off);
                    end[l] = end[l].max(fin);
                    if RESIDENT_SMALL.iter().any(|s| name.ends_with(s)) {
                        small[l] += size;
                    }
                }
                None => {
                    non_layer.push((name.to_string(), size));
                    nl_start = nl_start.min(off);
                    nl_end = nl_end.max(fin);
                    nl_sum += size;
                }
            }
        }
        for l in 0..n_blocks {
            assert_eq!(LAYERS[l], (start[l], end[l], small[l]), "layer {l}");
        }
        let input = plan_input();
        assert_eq!(input.non_layer, non_layer);
        assert_eq!(input.non_layer_region, if nl_end - nl_start <= nl_sum + nl_sum / 8 { Some((nl_start, nl_end)) } else { None });
        assert_eq!(input.n_layer as usize + input.mtp.len(), n_blocks);
        assert_eq!(input.layer_span.len(), N_LAYER as usize);
        // every layer is contiguous with the next: the spans tile the data region up to the end of the file
        for l in 1..n_blocks {
            assert_eq!(LAYERS[l].0, LAYERS[l - 1].1, "gap before layer {l}");
        }
        assert_eq!(LAYERS[n_blocks - 1].1, FILE_SIZE);
        assert_eq!(LAYERS[0].0, nl_end);
    }

    /// With the real file on this machine, the table must be exactly what the engine builds from it.
    #[test]
    fn table_matches_the_real_file_when_present() {
        let path = std::env::var_os("AQUEDUCT_GGUF").map(PathBuf::from).unwrap_or_else(|| PathBuf::from(crate::run::DEFAULT_GGUF));
        if !path.exists() {
            if std::env::var_os("AQUEDUCT_REQUIRE_MODEL").is_some() {
                panic!("primary GGUF missing at {} and AQUEDUCT_REQUIRE_MODEL is set", path.display());
            }
            eprintln!("SKIPPED: primary GGUF missing at {} (set AQUEDUCT_GGUF)", path.display());
            return;
        }
        let g = aqueduct_core::Gguf::open(&path).expect("open");
        let cfg = aqueduct_core::ModelConfig::from_gguf(&g).expect("config");
        let from_file = PlanInput::new(&g, &cfg);
        assert_eq!(format!("{:?}", from_file), format!("{:?}", plan_input()));
        assert_eq!(std::fs::metadata(&path).unwrap().len(), FILE_SIZE);
    }
}
