"""Index a remote GGUF's metadata and tensor table WITHOUT downloading its tensor data.

A GGUF file starts with the magic, version, tensor count, KV metadata, then the tensor-info table;
tensor data follows after alignment padding. We fetch the first `--bytes` of the file with an HTTP
Range request (default 32 MiB; the MTP head file has a small vocab-free header) and parse it with
gguf-py's GGUFReader, overriding the step that would touch tensor data.

Writes tests/fixtures/gguf_metadata.<tag>.json, tests/fixtures/gguf_index.<tag>.json and
docs/data/gguf_layout.<tag>.txt via tools/gguf_index.py's functions (with --no-st semantics).

Usage: python tools/gguf_header_probe.py <repo_id> <path/in/repo.gguf> --tag mtp [--bytes 33554432]
Uses HF_TOKEN from the environment if set.
"""
import argparse
import json
import os
import sys

import numpy as np
import requests
from gguf import GGUFReader, GGMLQuantizationType
from gguf.constants import GGML_QUANT_SIZES
from gguf.gguf_reader import ReaderTensor
from huggingface_hub import hf_hub_url

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gguf_index as GI  # noqa: E402


class HeaderOnlyReader(GGUFReader):
    """GGUFReader that records tensor infos but never slices tensor data (file may be truncated)."""

    def _build_tensors(self, start_offs, fields):
        tensors = []
        for field in fields:
            _name_len, name_data, _n_dims, dims, raw_dtype, offset_tensor = field.parts
            name = str(bytes(name_data), encoding="utf-8")
            ggml_type = GGMLQuantizationType(raw_dtype[0])
            n_elems = int(np.prod(dims))
            block_size, type_size = GGML_QUANT_SIZES[ggml_type]
            n_bytes = n_elems * type_size // block_size
            tensors.append(ReaderTensor(name=name, tensor_type=ggml_type, shape=dims, n_elements=n_elems,
                                        n_bytes=n_bytes, data_offset=int(start_offs + offset_tensor[0]),
                                        data=None, field=field))
        self.tensors = tensors


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("repo_id")
    ap.add_argument("path")
    ap.add_argument("--tag", required=True)
    ap.add_argument("--bytes", type=int, default=32 * 2**20)
    a = ap.parse_args()
    token = os.environ.get("HF_TOKEN")
    url = hf_hub_url(a.repo_id, a.path)
    headers = {"Range": "bytes=0-%d" % (a.bytes - 1)}
    if token:
        headers["Authorization"] = "Bearer " + token
    r = requests.get(url, headers=headers, allow_redirects=True, timeout=120)
    r.raise_for_status()
    assert r.status_code == 206, r.status_code
    total = int(r.headers.get("Content-Range", "bytes 0-0/0").split("/")[-1])
    local_dir = os.path.join(GI.ROOT, "models", "_headers")
    os.makedirs(local_dir, exist_ok=True)
    local = os.path.join(local_dir, os.path.basename(a.path) + ".head")
    with open(local, "wb") as fh:
        fh.write(r.content)
    print("fetched %d bytes of %d (%s)" % (len(r.content), total, a.path))

    reader = HeaderOnlyReader(local, "r")
    assert int(reader.data_offset) <= len(r.content), "header longer than fetched prefix; raise --bytes"
    os.makedirs(GI.FIX, exist_ok=True)
    os.makedirs(GI.DOCS, exist_ok=True)
    GI.dump_metadata(reader, os.path.join(GI.FIX, "gguf_metadata.%s.json" % a.tag))
    recs = GI.tensor_records(reader)
    with open(os.path.join(GI.FIX, "gguf_index.%s.json" % a.tag), "w", encoding="utf-8") as fh:
        json.dump({"file": a.path, "repo": a.repo_id, "file_size": total, "header_only": True,
                   "alignment": int(reader.alignment), "data_offset": int(reader.data_offset),
                   "n_tensors": len(recs), "tensors": recs}, fh, indent=1)
    lines = ["# generated by tools/gguf_header_probe.py: HEADER-ONLY scan of %s/%s (%d bytes fetched of %d)" % (a.repo_id, a.path, len(r.content), total),
             "# file size below is the fetched prefix, NOT the real file; real size is %d bytes" % total, ""]
    # layout_report uses os.path.getsize for the file size line; the real size is stated above
    GI.layout_report(reader, recs, local, lines)
    out = os.path.join(GI.DOCS, "gguf_layout.%s.txt" % a.tag)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("\n".join(lines))
    print("\nwrote", out)


if __name__ == "__main__":
    main()
